# Generated by Django 2.2 on 2019-04-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("location", models.CharField(max_length=120)),
                ("publication_date", models.DateField()),
                ("draft", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
